MONGODB_HOST: mongodb-{{ env }}.kidevops.shop
REDIS_HOST: redis-{{ env }}.kidevops.shop
CATALOGUE_HOST: catalogue-{{ env }}.kidevops.shop
CART_HOST: cart-{{ env }}.kidevops.shop
MYSQL_HOST: mysql-{{ env }}.kidevops.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.kidevops.shop
PAYMENT_HOST: payment-{{ env }}.kidevops.shop
USER_HOST: user-{{ env }}.kidevops.shop
SHIPPING_HOST: shipping-{{ env }}.kidevops.shop



